// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLOq1U0X9L140QfcV7hNyB3bVP04bhnE',
    appId: '1:480680793734:web:ad5af422d9ba9b040d6307',
    messagingSenderId: '480680793734',
    projectId: 'gallery-one-6c3d6',
    authDomain: 'gallery-one-6c3d6.firebaseapp.com',
    databaseURL: 'https://gallery-one-6c3d6-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-one-6c3d6.appspot.com',
    measurementId: 'G-Q0MCE0MN0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyqDs4LMBsTdEHzzwe6_3ZVvv2G7_Z7Q',
    appId: '1:480680793734:android:152c25b9078c33430d6307',
    messagingSenderId: '480680793734',
    projectId: 'gallery-one-6c3d6',
    databaseURL: 'https://gallery-one-6c3d6-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-one-6c3d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3eEOsNR2W48z5FS57ZQwx2SGzFh6Vgik',
    appId: '1:480680793734:ios:c3e8581bc1d10dc00d6307',
    messagingSenderId: '480680793734',
    projectId: 'gallery-one-6c3d6',
    databaseURL: 'https://gallery-one-6c3d6-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-one-6c3d6.appspot.com',
    iosClientId: '480680793734-u75h2v931gct54b5d4j2lp1r3sampunp.apps.googleusercontent.com',
    iosBundleId: 'com.exam',
  );
}
